env:
  commonjs: true
  es2021: true
  node: true
ignorePatterns:
  - "dist/**/*"
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - 2
    - 2
  linebreak-style:
    - 2
    - unix
  quotes:
    - 2
    - single
  semi:
    - 2
    - never
  no-debugger: 1
  no-console: 1
  no-duplicate-imports: 2
  no-undef-init: 2
  no-use-before-define: 2
  prefer-const: 1
  no-multiple-empty-lines: 2
  no-multi-spaces: 2
  no-var: 2
  no-useless-rename: 2
  no-useless-return: 2
  require-await: 2
  eqeqeq: 2
