components:
    Cat:
      type: object
      properties:
        name:
          type: string
        profileImage:
          type: string
        tag:
          type: array
          items:
            type: string
    Content:
      type: object
      properties:
        title:
          type: string



