components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        profileImage:
          type: string
    Cat:
      type: object
      properties:
        name:
          type: string
        profileImage:
          type: string
        tag:
          type: array
          items:
            type: string
    Content:
      type: object
      properties:
        title:
          type: string



