tags:
  name: User
  description: User 관련 API


paths:
  /user/signup:
    post:
      tags:
      - User
      summary: 회원가입 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickName:
                  type: string
                  description: 사용자 nickname
                email:
                  type: string
                  description: login Id 로 사용할 email 주소
                mobileNo:
                  type: string
                  description: 전화번호
                password:
                  type: string
                  description: 비밀번호
                passwordConfirm:
                  type: string
                  description: 비밀번호 확인
                gender:
                  type: string
                  enum: [M, F]
                  description: 성별
              required:
              - nickName
              - email
              - password
              - passwordConfirm
              - gender
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        400:
          description: |
            `Required Body` body에 필수값 누락

            `Invalid gender value` gender는 M 또는 F 여야만 함
            
            `Invalid PasswordType` 비밀번호 요구사항 미달 - 8~20자리 숫자와 문자 최소 1개 포함

            `Unmatched password and passwordConfirm` 비밀번호와 비밀번호확인 불일치

            `Id Already exists` 이미 존재하는 login Id (email 주소)
        500:
          description: '**관리자에게 문의하세요**'
  /user/signin:
    post:
      tags:
      - User
      summary: 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loginId:
                  type: string
                password:
                  type: string
              required:
              - loginId
              - password
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  userToken:
                    type: string
                    description: 로그인시 부여되는 토큰
        400:
          description: |
            `Required Body` 로그인ID 또는 password 누락

            `Invalid loginId or password` 로그인 ID 또는 password가 잘못됨
        500:
          description: '**관리자에게 문의하세요**'
  /user/delete-code:
    get:
      tags: 
      - User
      summary: 회원탈퇴시 랜덤코드 발급 (유효시간 5분)
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: Ay0xgt
        403:
          description: '`Forbidden` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
  /user/deactivate:
    post:
      tags:
      - User
      summary: 회원탈퇴 API
      parameters:
      - in: query
        name: code
        schema:
          type: string
          example: Ay0xgt
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        400:
          description: '`BadRequest` 코드를 입력하지 않거나 유효하지 않은 코드 입력'
        403:
          description: '`Forbidden` token 만료'
        500:
          description: '**관리자에게 문의하세요**'


components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        loginId:
          type: string
        nickName:
          type: string
        email:
          type: string
        mobileNo:
          type: string
