tags:
  name: User
  description: User 관련 API


paths:
  /user:
    get:
      tags:
      - User
      security:
      - token: []
      summary: 사용자 정보 API
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        403:
          description: '`Unauthorized` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
    patch:
      tags:
      - User
      security:
      - token: []
      summary: 회원정보 수정 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                gender:
                  type: string
                instroduction:
                  type: string
        required: true
      responses:
        200:
          $ref: '#/responses/OK'
        400:
          description: '`Invalid gender value` gender 포함시 M이거나 F가 아닐 때'
        403:
          description: '`Forbidden` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
  /user/check:
    get:
      tags:
      - User
      summary: nickname 또는 email주소 중복확인
      parameters:
      - in: query
        name: nickname
        schema:
          type: string
      - in: query
        name: email
        schema:
          type: string
      responses:
        200:
          $ref: '#/responses/OK'
        400:
          description: |
            `Required nickname or email` nickname과 email 모두 누락 (최소 하나의 값은 필수)

            `email already exists` 동일한 email 주소 이미 사용중

            `nickname already exists` 동일한 nickname 이미 사용중
        500:
          description:
            '**관리자에게 문의하세요**'

  /user/signup:
    post:
      tags:
      - User
      summary: 회원가입 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                  description: 사용자 nickname
                email:
                  type: string
                  description: login Id 로 사용할 email 주소
                mobileNo:
                  type: string
                  description: 전화번호
                password:
                  type: string
                  description: 비밀번호
                passwordConfirm:
                  type: string
                  description: 비밀번호 확인
                gender:
                  type: string
                  enum: [M, F]
                  description: 성별
              required:
              - nickname
              - email
              - password
              - passwordConfirm
              - gender
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        400:
          description: |
            `Required Body` body에 필수값 누락

            `Invalid gender value` gender는 M 또는 F 여야만 함
            
            `Invalid PasswordType` 비밀번호 요구사항 미달 - 8~20자리 숫자와 문자 최소 1개 포함

            `Unmatched password and passwordConfirm` 비밀번호와 비밀번호확인 불일치
        500:
          description: '**관리자에게 문의하세요**'
  /user/signin:
    post:
      tags:
      - User
      summary: 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loginId:
                  type: string
                password:
                  type: string
              required:
              - loginId
              - password
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  userToken:
                    type: string
                    description: 로그인시 부여되는 토큰
        400:
          description: |
            `Required Body` 로그인ID 또는 password 누락

            `Invalid loginId or password` 로그인 ID 또는 password가 잘못됨
        500:
          description: '**관리자에게 문의하세요**'
  /user/delete-code:
    get:
      tags: 
      - User
      security:
      - token: []
      summary: 회원탈퇴시 랜덤코드 발급 (유효시간 5분)
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: Ay0xgt
        403:
          description: '`Unauthorized` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
  /user/deactivate:
    post:
      tags:
      - User
      security:
      - token: []
      summary: 회원탈퇴 API
      parameters:
      - in: query
        name: code
        schema:
          type: string
          example: Ay0xgt
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        400:
          description: '`Invalid Code` 코드를 입력하지 않거나 유효하지 않은 코드 입력'
        403:
          description: '`Unauthorized` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
  /user/password:
    put:
      tags:
      - User
      security:
      - token: []
      summary: 비밀번호 변경 API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: 사용하던 비밀번호
                newPassword:
                  type: string
                  description: 변경 할 비밀번호
                newPasswordConfirm:
                  type: string
                  description: 변경 할 비밀번호확인
              required:
              - password
              - newPassword
              - newPasswordConfirm
        required: true
      responses:
        200:
          $ref: '#/responses/OK'
        400:
          description: |
            `Required Body` password, newPassword, newPasswordConfirm 누락

            `Invalid password` 비밀번호 불일치
            
            `Password must be New` 기존 비밀번호와 같음

            `Invalid PasswordType` 비밀번호 규칙위반 (8~20자리 문자, 숫자 1개이상 필수)

            `Unmatched newPassword and newPasswordConfirm` 변경할 비밀번호와 확인 불일치
        403:
          description: '`Unauthorized` token 만료'
        500:
          description: '**관리자에게 문의하세요**'
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        loginId:
          type: string
        nickname:
          type: string
        email:
          type: string
        mobileNo:
          type: string
        gender:
          type: string
        lastAccessedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        socialId:
          type: string
        introduction:
          type: string
      required:
      - _id
      - loginId
      - nickname
      - gender
      - createdAt
      - updatedAt
      - lastAccessedAt

responses:
  OK:
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
              example : 'OK'

